export const banner1heading:string = "Everything you are. In one, simple link in bio.";
export const banner1pargraph:string = "Join 35M+ people using Synctree for their link in bio. One link to help you share everything you create, curate and sell from your Instagram, TikTok, Twitter, YouTube and other social media profiles.";
export const button1text:string = "Claim Your Synctree"
export const banner2heading:string = "Create and customize your Synctree in minutes"
export const banner2pargraph:string = "Connect your TikTok, Instagram, Twitter, website, store, videos, music, podcast, events and more. It all comes together in a link in bio landing page designed to convert."
export const button2Color:string = "#502274"
export const button2TextColor:string = "#ffffff"
export const banner3heading:string = "Share your Synctree from your Instagram, TikTok, Twitter and other bios"
export const banner3pargraph:string = "Add your unique Synctree URL to all the platforms and places you find your audience. Then use your QR code to drive your offline traffic online."
export const banner4heading:string = "Analyze your audience and keep your followers engaged";
export const banner4pargraph:string = "Track your engagement over time, monitor revenue and learn what’s converting your audience. Make informed updates on the fly to keep them coming back.";
export const homeCard1content:string = "Connect with all the Important Meta Applications like FB, Insta, etc."
export const homeCard2content:string = "Connect with Twitch, Twitter or Medium and share your video/post links."
export const homeCard3content:string = "Connect with Google, Messenger or your Youtube Channel and gain more subs."