import "./globals.css";
import { Metadata } from "next";
import Providers from "./components/Themeprovider";
import Header from "./components/header/Header";
import Themechanger from "./components/Themechanger";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html>
      <body>
        <Providers>
          <div className="overflow-x-hidden">
            <Header />
            <Themechanger />
            {children}
          </div>
        </Providers>
      </body>
    </html>
  );
}
