import "./globals.css";
import { Metadata } from "next";
import Header from "./components/header/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html>
      <body>
        <div className="overflow-x-hidden">
          <Header />
          {children}
        </div>
      </body>
    </html>
  );
}
