import { Metadata } from "next";

export async function generateMetadata({
  params,
}: {
  params: { username: string };
}): Promise<Metadata> {
  return {
    title: `${params.username.slice(3).toLowerCase()}`,
    description: "Generated by create next app",
  };
}
export default function Layout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
      <div>
        {children}
      </div>
  );
}
